<div class="modal fade" id="modal-form-mappinggaji" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog modal-dialog-centered modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title pull-left">
                    <?= (isset($card_title)) ? $card_title : 'Input' ?>
                </h5>
            </div>
            <div class="spinner">
                <div class="lds-hourglass"></div>
            </div>
            <div class="modal-body">
                <form id="form-mappinggaji" autocomplete="off">
                    <!-- CSRF -->
                    <input type="hidden" name="<?= $this->security->get_csrf_token_name(); ?>" value="<?= $this->security->get_csrf_hash(); ?>" readonly />
                    <input type="hidden" name="ref" value="<?= $key ?>" readonly />

                    <div class="row">
                        <div class="col-xs-12 col-sm-6">
                            <div class="form-group">
                                <label required>Unit</label>
                                <div class="select">
                                    <select name="unit_id" class="form-control select2-partial mappinggaji-unit_id" data-placeholder="Pilih &#8595;" required>
                                        <?= $unit_list ?>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-6">
                            <div class="form-group">
                                <label required>Sub Unit</label>
                                <div class="select">
                                    <select name="sub_unit_id" class="form-control select2-partial mappinggaji-sub_unit_id" data-placeholder="Pilih &#8595;" required>
                                        <?= $sub_unit_list ?>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12 col-sm-6">
                            <div class="form-group">
                                <label required>Jabatan</label>
                                <div class="select">
                                    <select name="jabatan_id" class="form-control select2-partial mappinggaji-jabatan_id" data-placeholder="Pilih &#8595;" required>
                                        <?= $jabatan_list ?>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-6">
                            <div class="form-group">
                                <label required>Status Pegawai</label>
                                <div class="select">
                                    <select name="jenis_pegawai_id" class="form-control select2-partial mappinggaji-jenis_pegawai_id" data-placeholder="Pilih &#8595;" required>
                                        <?= $jenis_pegawai_list ?>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="x-section-group mb-2">
                        <span class="x-section-group-title">Indikator</span>
                        <div class="x-section-group-body">
                            <a href="javascript:;" class="btn btn-primary btn-sm mappinggaji-indikator-add">
                                <i class="zmdi zmdi-plus"></i> Tambah
                            </a>
                            <hr />
                            <div class="indikator-collection mb-2">
                                <!-- Content generated by javascript : load_indikatorItem() -->
                            </div>
                            <div class="alert alert-warning p-2 m-0">
                                <small>
                                    <i class="zmdi zmdi-alert-triangle"></i> <b>Aturan Expression</b>
                                    <ul class="m-0" style="padding-left: 15px;">
                                        <li>Jika menggunakan indikator lain pastikan penamaan alias & huruf besar / kecil nya sama persis (case-sensitive)</li>
                                        <li>Penulisan angka / nominal tidak boleh ada format uang, untuk desimal gunakan titik (Contoh : 1500.25)</li>
                                        <li>Untuk perhitungan pastikan penulisan aritmatika seperti kurung buka tutup nya sudah benar</li>
                                    </ul>
                                </small>
                            </div>
                        </div>
                    </div>

                    <small class="form-text text-muted">
                        Fields with red stars (<label required></label>) are required.
                    </small>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-success btn--icon-text mappinggaji-action-save">
                    <i class="zmdi zmdi-save"></i> Simpan
                </button>
                <button type="button" class="btn btn-light btn--icon-text mappinggajiaction-cancel" data-dismiss="modal">
                    Tutup
                </button>
            </div>
        </div>
    </div>
</div>